[package]
name = "majin-blob"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num-bigint = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
bitvec = "1.0.1"
